### ISSUE TITLE
N and W not snapping - v1.9

### ISSUE THREAD

**Issue by tnt6200** [polomoshnov/jQuery-UI-Resizable-Snap-extension#5]
The north and west sides do not seem to be snapping in 1.9. South and east work fine, though. All sides work in 1.8.

**Comment by polomoshnov** [comment]
[A new version](https://github.com/polomoshnov/jQuery-UI-Resizable-Snap-extension/releases/tag/v1.9.1) has been just released. You can test it at http://polomoshnov.github.io/jQuery-UI-Resizable-Snap-extension/. Let me know if it doesn't work for you.
